### ISSUE TITLE
python cscb.py Traceback (most recent call last):   File "cscb.py", line 274, in <module> 

### ISSUE THREAD

**Issue by mrranger** [Mikooboy/csgo-chat-bot#1]
C:\Users\RANGERSTUDIO\Desktop\csgo-chat-bot-main>python cscb.py
Traceback (most recent call last):
  File "cscb.py", line 274, in <module>
    main()
  File "cscb.py", line 60, in main
    if not processExists("csgo.exe"):
  File "cscb.py", line 41, in processExists
    if proc.info['name'].lower() == processName.lower():
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by Mikooboy** [comment]
Added an exception handler when getting process names
